SWIDEA_SITE/config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('ideas.urls')),
    path('', include('tools.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

SWIDEA_SITE/ideas/urls.py
from django.urls import path
from .views import *

app_name = 'ideas'

urlpatterns = [
    path('', idea_list, name='idea_list'),
    path('detail/<int:pk>/', idea_detail, name="idea_detail"),
    path('create/', idea_create, name="idea_create"),
    path('delete/<int:pk>/', idea_delete, name="idea_delete"),
    path('update/<int:pk>/', idea_update, name="idea_update"),
    path('update_like/', update_like, name='update_like'),
    path('update_interest/<int:idea_id>/', update_interest, name="update_interest"),
]

SWIDEA_SITE/tools/urls.py
from django.urls import path
from .views import *

app_name = 'tools'

urlpatterns = [
    path('tool/', tool_list, name="tool_list"),
    path('tool/detail/<int:pk>/', tool_detail, name="tool_detail"),
    path('tool/delete/<int:pk>/', tool_delete, name="tool_delete"),
    path('tool/update/<int:pk>/', tool_update, name="tool_update"),
    path('tool/create/', tool_create, name="tool_create"),
]

SWIDEA_SITE/ideas/models.py
from django.db import models
from tools.models import Tool

class Idea(models.Model):
    title = models.CharField('아이디어명', max_length=20)
    image = models.ImageField('Image', upload_to='images/%Y%m%d', blank=True)
    explain = models.TextField('아이디어 설명')
    interest = models.IntegerField('아이디어 관심도')
    develop_tool = models.ForeignKey(Tool, verbose_name='예상 개발툴', on_delete=models.CASCADE)
    created_at = models.DateTimeField('최초 등록시간', auto_now_add=True)
    updated_at = models.DateTimeField('최종 수정시간', auto_now=True)
    is_like = models.BooleanField(default=False)

SWIDEA_SITE/tools/models.py
from django.db import models

class Tool(models.Model):
    name = models.CharField('이름', max_length=20)
    type = models.CharField('종류', max_length=20)
    explain = models.TextField('개발툴 설명')
    
    def __str__(self):
        return self.name

SWIDEA_SITE/ideas/forms.py
from django import forms 
from .models import Idea

class IdeaForm(forms.ModelForm):
    class Meta:
        model = Idea
        fields = ('__all__')

SWIDEA_SITE/tools/forms.py
from django import forms
from .models import Tool

class ToolFrom(forms.ModelForm):
    class Meta:
        model = Tool
        fields = ('__all__')

SWIDEA_SITE/ideas/views.py
from django.shortcuts import render, redirect
from django.urls import reverse
from django.http import JsonResponse
from django.views.decorators.csrf import csrf_exempt
import json
from .models import Idea
from .forms import IdeaForm

def idea_list(request):
    how_to_order = request.GET.get('order')
    if not how_to_order:
        how_to_order = 'created_at'
    ideas = Idea.objects.all().order_by(how_to_order)
    context = {
        'ideas': ideas
    }
    return render(request, 'ideas/list.html', context)

def idea_detail(request, pk):
    idea = Idea.objects.get(id=pk)
    context = {
        'idea': idea,
    }
    return render(request, 'ideas/detail.html', context)

def idea_create(request):
    if request.method == 'GET':
        form = IdeaForm()
        context = {
            'form': form 
        }
        return render(request, 'ideas/create.html', context)
    else:
        form = IdeaForm(request.POST, request.FILES)
        if form.is_valid():
            create_idea = form.save()
        return redirect('ideas:idea_detail', pk=create_idea.pk)
        

def idea_update(request, pk):
    if request.method == 'GET':
        idea = Idea.objects.get(id=pk)
        form = IdeaForm(instance=idea)
        context = {
            'form': form,
            'pk': pk
        }
        return render(request, 'ideas/update.html', context)
    else:
        idea = Idea.objects.get(id=pk)
        form = IdeaForm(request.POST, request.FILES, instance=idea)
        if form.is_valid():
            form.save()
        return redirect('ideas:idea_detail', pk)

def idea_delete(request, pk):
    if request.method == 'POST':
        idea = Idea.objects.get(id=pk)
        idea.delete()
        return redirect("ideas:idea_list")
    return redirect("ideas:idea_list")

@csrf_exempt
def update_like(request):
    if request.method == 'POST':
        data = json.loads(request.body)
        idea_id = data.get('like_idea_id')
        is_like = data.get('is_like')
        
        try:
            idea = Idea.objects.get(id=idea_id)
            idea.is_like = is_like
            idea.save()
            return JsonResponse({'success': True, 'is_like': idea.is_like, 'message': '관심 상태가 업데이트되었습니다.'})
        except Idea.DoesNotExist:
            return JsonResponse({'success': False, 'message': '관심 항목이 없습니다.'})
    return JsonResponse({'success': False, 'message': '잘못된 요청입니다.'}, status=400)

@csrf_exempt
def update_interest(request, idea_id):
    if request.method == 'POST':
        idea = Idea.objects.get(id=idea_id)
        action = request.POST.get('action')
        if action == 'plus':
            idea.interest += 1
        elif action == 'minus':
            idea.interest -= 1
        idea.save()
        return JsonResponse({"success": True, "update_interest": idea.interest})
    return JsonResponse({"success": False, "error": "Invalid request"}, status=400)

SWIDEA_SITE/tools/views.py
from django.shortcuts import render, redirect
from django.urls import reverse
from .models import Tool
from ideas.models import Idea

def tool_list(request):
    tools = Tool.objects.all()
    context = {
        'tools': tools
    }
    return render(request, 'tools/tool_list.html', context)

def tool_detail(request, pk):
    tool = Tool.objects.get(id=pk)
    related_ideas = Idea.objects.filter(develop_tool=tool).values('title', 'id')
    context = {
        'tool': tool,
        'related_ideas': related_ideas,
    }
    return render(request, 'tools/tool_detail.html', context)

def tool_create(request):
    if request.method == 'POST':
        tool = Tool.objects.create(
            name = request.POST['name'],
            type = request.POST['type'],
            explain = request.POST['explain'],
        )
        return redirect(reverse('tools:tool_list'))
    return render(request, 'tools/tool_create.html')

def tool_update(request, pk):
    exist_tool = Tool.objects.get(id=pk)
    if request.method == 'POST':
        name = request.POST.get('name')
        type = request.POST.get('type')
        explain = request.POST.get('explain')
        
        exist_tool.name = name
        exist_tool.type = type
        exist_tool.explain = explain
        exist_tool.save()
        return redirect('tools:tool_detail', pk=exist_tool.pk)
    context = {
        'tool': exist_tool,
    }
    return render(request, 'tools/tool_update.html', context)
    
def tool_delete(request, pk):
    if request.method == 'POST':
        tool = Tool.objects.get(id=pk)
        tool.delete()
        return redirect('tools:tool_list')
    return redirect('tools:tool_list')

SWIDEA_SITE/templates/ideas/detail.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap-icons/font/bootstrap-icons.css" rel="stylesheet">
    <title>My SW-IDEA Site</title>
    <style>
        *{
            box-sizing: border-box;
        }
        @font-face {
            font-family: 'ChosunGu';
            src: url('https://fastly.jsdelivr.net/gh/projectnoonnu/noonfonts_20-04@1.0/ChosunGu.woff') format('woff');
            font-weight: normal;
            font-style: normal;
        }
        body{
            font-family: 'ChosunGu';
            font-size: 20px;
        }
        header {
            display: flex;
            justify-content: space-between;
            padding-block: 20px;
            padding-inline: 80px;
            border-bottom: 2px solid Gainsboro;
        }
        .left_nav_container{
            font-weight: 700;
            text-decoration: none;
            color: black;
        }
        .green{
            color: Turquoise;
        }
        .right_nav_container{
            display: flex;
            gap: 140px;
        }
        .nav_menu, .nav_menu:visited {
            font-family: 'ChosunGu';
            font-size: 20px;
            text-decoration: none;
            color: black;
        }
        .under_navBar {
            padding: 50px;
            height: 100vh;
            background-color: Tan;
        }
        .idea_list_container {
            margin-inline: 10%;
            padding: 50px;
            padding-top: 70px;
            display: flex;
            justify-content: center;
            align-items: center;
            height:100%;
            background-color: Linen;
            border-radius: 4px;
            border-top: 23px dashed Tan;
        }
        .idea_list {
            display: flex;
            flex-direction: column;
            align-items: center;
            width: 100%;
            height: 100%;
        }
        .idea_list_intro {
            display: flex;
            flex-direction: column;
            align-items: center;
        }
        .idea_list_title {
            font-weight: 700;
            font-size: 24px;
        }
        .idea_list_intro_detail {
            display: flex;
            align-items: center;
            font-size: 18px;
        }
        .idea_list_content {
            display: flex;
            height: 100%;
            width: 100%;
            justify-content: center;
            gap: 80px;
            margin-top: 40px;
        }
        .idea_card {
            padding: 8px;
            display: flex;
            justify-content: center;
            width: 94%;
            height: 100%;
            background-color:rgba(162, 255, 246, 0.5);
            border-radius: 10px;
            position: relative;
        }
        .idea_img {
            width: 300px;
            height: 300px;
            margin: 10px;
            border-radius: 10px;
            overflow: hidden;
        }
        .img {
            width: 100%;
            height: 100%;
        }
        .idea_card_left {
            height: 100%;
            padding-top: 40px;
        }
        .idea_card_right {
            margin-left: 30px;
            width: 500px;
            height: 80%;
            padding-block: 40px;
            display: flex;
            flex-direction: column;
            align-items: left;
            font-size: 18px;
        }
        .idea_title{
            margin-top: 20px;
            font-weight: 700;
            font-size: 36px;
            display: flex;
        }
        .bi-star, .bi-star-fill{
            color: gold;
            font-size: 30px;
            font-weight: 500;
            position: absolute;
            left: 720px;
        }
        .behind {
            opacity: 0%;
        }
        .idea_interest, .idea_devtool, .idea_explain {
            display: flex;
            flex-direction: column;
            gap: 2px;
            margin-bottom: 30px;
        }
        .buttons{
            position: absolute;
            bottom: 40px;
            display: flex;
            gap: 30px;
        }
        .delete_btn, .list_btn, .update_btn {
            font-size: 16px;
            font-family: 'ChosunGu';
            font-weight: 700;
            padding-inline: 14px;
            padding-block: 10px;
            border: 1px solid Gainsboro;
            border-radius: 6px;
        }
        .delete_btn {
            background-color:rgb(246, 88, 119);
        }
        .update_btn {
            background-color:rgb(160, 218, 103);
        }
        .link, .link:visited {
            text-decoration: none;
            color: black;
            font-size: 22px;
            font-weight: 700;
        }
    </style>
</head>
<body>
    <header>
        <a href="{% url 'ideas:idea_list' %}" class="left_nav_container">My <span class="green">SW Idea</span> Manage</a>
        <div class="right_nav_container">
            <a href="{% url 'ideas:idea_create' %}" class="nav_menu">아이디어 등록</a>
            <a href="{% url 'ideas:idea_list' %}" class="nav_menu">아이디어 관리</a>
            <a href="{% url 'tools:tool_create' %}" class="nav_menu">개발툴 등록</a>
            <a href="{% url 'tools:tool_list' %}" class="nav_menu">개발툴 관리</a>
        </div>
    </header>
    <div class="under_navBar">
        <div class="idea_list_container">
            <div class="idea_list">
                <div class="idea_list_intro">
                    <div class="idea_list_title">💡Idea Detail🔍</div>
                    <div class="idea_list_intro_detail">
                        <p>아이디어 세부사항 페이지 입니다. 당신이 구현하려 한 아이디어들을 자세히 살펴보세요!</p>
                    </div>
                </div>
                <div class="idea_list_content">
                    <div class="idea_card">
                        <div class="idea_card_left">
                            <div class="idea_img"><img src="{{idea.image.url}}" alt="" class="img"></div>
                        </div>
                        <div class="idea_card_right">
                            <div class="idea_title" data-is-like="{{idea.is_like}}">{{idea.title}}
                                <i class="like_btn bi bi-star"></i>
                                <i class="like_btn bi bi-star-fill behind"></i>
                            </div>
                            <div class="idea_interest">
                                <p>1) 아이디어 관심도<div>{{idea.interest}}</div>
                            </div>
                            <div class="idea_devtool">
                                <p>2) 예상 개발툴<div><a href="{% url 'tools:tool_detail' idea.develop_tool_id %}" class="link">{{idea.develop_tool.name}}</a></div>
                            </div>
                            <div class="idea_explain">
                                <p>3) 아이디어 설명<div>{{idea.explain}}</div>
                            </div>
                        </div>
                        <div class="buttons">
                            <form action="{% url "ideas:idea_delete" idea.pk %}" method="post">
                                {% csrf_token %}
                                <button type="submit" class="delete_btn">삭제</button>
                            </form>
                            <form action="{% url "ideas:idea_list" %}">
                                {% csrf_token %}
                                <button type="submit" class="list_btn">목록</button>
                            </form>
                            <form action="{% url "ideas:idea_update" idea.pk %}">
                                {% csrf_token %}
                                <button type="submit" class="update_btn">수정</button>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <script>
        const parent = document.querySelector(".idea_title");
        const filled_star = parent.querySelector(".bi-star-fill");
        const is_like = parent.dataset.isLike === "True";
        if(is_like) {
            filled_star.classList.remove('behind');
        }
        else {
            filled_star.classList.add('behind');
        }
    </script>
</body>
</html>

SWIDEA_SITE/templates/ideas/update.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>My SW-IDEA Site</title>
    <style>
        *{
            box-sizing: border-box;
        }
        @font-face {
            font-family: 'ChosunGu';
            src: url('https://fastly.jsdelivr.net/gh/projectnoonnu/noonfonts_20-04@1.0/ChosunGu.woff') format('woff');
            font-weight: normal;
            font-style: normal;
        }
        body{
            font-family: 'ChosunGu';
            font-size: 20px;
        }
        header {
            display: flex;
            justify-content: space-between;
            padding-block: 20px;
            padding-inline: 80px;
            border-bottom: 2px solid Gainsboro;
        }
        .left_nav_container{
            font-weight: 700;
            text-decoration: none;
            color: black;
        }
        .green{
            color: Turquoise;
        }
        .right_nav_container{
            display: flex;
            gap: 140px;
        }
        .nav_menu, .nav_menu:visited {
            font-family: 'ChosunGu';
            font-size: 20px;
            text-decoration: none;
            color: black;
        }
        .under_navBar {
            padding: 50px;
            height: 100vh;
            background-color: Tan;
        }
        .idea_list_container {
            margin-inline: 10%;
            padding: 50px;
            padding-top: 70px;
            display: flex;
            justify-content: center;
            align-items: center;
            height:100%;
            background-color: Linen;
            border-radius: 4px;
            border-top: 23px dashed Tan;
        }
        .idea_list {
            display: flex;
            flex-direction: column;
            align-items: center;
            width: 100%;
            height: 100%;
        }
        .idea_list_intro {
            display: flex;
            flex-direction: column;
            align-items: center;
        }
        .idea_list_title {
            font-weight: 700;
            font-size: 24px;
        }
        .idea_list_intro_detail {
            display: flex;
            align-items: center;
            font-size: 18px;
        }
        .idea_list_content {
            display: flex;
            height: 100%;
            width: 100%;
            justify-content: center;
            gap: 80px;
            margin-top: 40px;
        }
        form {
            width: 100%;
        }
        .idea_card {
            padding: 8px;
            display: flex;
            justify-content: center;
            width: 100%;
            height: 100%;
            background-color:rgba(162, 255, 246, 0.5);
            border-radius: 10px;
            position: relative;
        }
        .idea_img {
            width: 300px;
            height: 300px;
            margin: 10px;
            border-radius: 10px;
            overflow: hidden;
        }
        .img {
            width: 100%;
            height: 100%;
        }
        .idea_title {
            margin-top: 20px;
        }
        .idea_card_right {
            margin-left: 30px;
            width: 500px;
            height: 80%;
            padding-block: 40px;
            display: flex;
            justify-content: space-between;
            flex-direction: column;
            font-size: 18px;
        }
        .image > p {
            margin-block: 3px;
        }
        .textarea {
            display: flex;
            flex-direction: column;
            gap: 5px;
        }
        .buttons{
            position: absolute;
            bottom: 40px;
        }
        .submit_btn {
            background-color:rgb(44, 250, 226);
            font-size: 20px;
            font-family: 'ChosunGu';
            font-weight: 700;
            padding-inline: 14px;
            padding-block: 10px;
            border: 1px solid Gainsboro;
            border-radius: 6px;
        }
    </style>
</head>
<body>
    <header>
        <a href="{% url 'ideas:idea_list' %}" class="left_nav_container">My <span class="green">SW Idea</span> Manage</a>
        <div class="right_nav_container">
            <a href="{% url 'ideas:idea_create' %}" class="nav_menu">아이디어 등록</a>
            <a href="{% url 'ideas:idea_list' %}" class="nav_menu">아이디어 관리</a>
            <a href="{% url 'tools:tool_create' %}" class="nav_menu">개발툴 등록</a>
            <a href="{% url 'tools:tool_list' %}" class="nav_menu">개발툴 관리</a>
        </div>
    </header>
    <div class="under_navBar">
        <div class="idea_list_container">
            <div class="idea_list">
                <div class="idea_list_intro">
                    <div class="idea_list_title">💡Idea Detail Update🔧</div>
                    <div class="idea_list_intro_detail">
                        <p>아이디어 세부내용 수정 페이지입니다. 아이디어를 구체화하거나 내용을 변경해보아요~</p>
                    </div>
                </div>
                <div class="idea_list_content">
                    <form action="{% url 'ideas:idea_update' pk %}" method="post" enctype="multipart/form-data">
                        {% csrf_token %}
                        <div class="idea_card">
                            <div class="idea_card_right">
                                {{form.as_p}}
                            </div>
                            <div class="buttons">
                                <button type="submit" class="submit_btn">SUBMIT</button>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</body>
</html>

SWIDEA_SITE/templates/tools/tool_detail.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap-icons/font/bootstrap-icons.css" rel="stylesheet">
    <title>My SW-IDEA Site</title>
    <style>
        *{
            box-sizing: border-box;
        }
        @font-face {
            font-family: 'ChosunGu';
            src: url('https://fastly.jsdelivr.net/gh/projectnoonnu/noonfonts_20-04@1.0/ChosunGu.woff') format('woff');
            font-weight: normal;
            font-style: normal;
        }
        body{
            font-family: 'ChosunGu';
            font-size: 20px;
        }
        header {
            display: flex;
            justify-content: space-between;
            padding-block: 20px;
            padding-inline: 80px;
            border-bottom: 2px solid Gainsboro;
        }
        .left_nav_container{
            font-weight: 700;
            text-decoration: none;
            color: black;
        }
        .green{
            color: Turquoise;
        }
        .right_nav_container{
            display: flex;
            gap: 140px;
        }
        .nav_menu, .nav_menu:visited {
            font-family: 'ChosunGu';
            font-size: 20px;
            text-decoration: none;
            color: black;
        }
        .under_navBar {
            padding: 50px;
            height: 100vh;
            background-color: Tan;
        }
        .tool_list_container {
            padding: 50px;
            padding-top: 70px;
            display: flex;
            justify-content: center;
            align-items: center;
            height:100%;
            background-color: Linen;
            border-radius: 4px;
            border-top: 25px dashed Tan;
        }
        .tool_list {
            display: flex;
            flex-direction: column;
            align-items: center;
            width: 100%;
            height: 100%;
        }
        .tool_list_intro {
            display: flex;
            flex-direction: column;
            align-items: center;
        }
        .tool_list_title {
            font-weight: 700;
            font-size: 30px;
        }
        .tool_list_intro_detail {
            display: flex;
            align-items: center;
            position: relative;
            font-size: 18px;
        }

        .tool_list_content {
            display: flex;
            flex-direction: column;
            height: 100%;
            width: 100%;
            gap: 10px;
            margin-block: 60px;
            align-items: center;
        }
        .tool_card {
            padding: 20px;
            display: flex;
            flex-direction: column;
            width: 100%;
            background-color:rgba(162, 255, 246, 0.5);
            border-radius: 10px;
            font-size: 18px;
            position: relative;
            gap: 10px;
        }
        .tool_card_content{
            display: flex;
            flex-direction: column;
            gap: 40px;
            padding-inline: 40px;
            padding-block: 14px;
        }
        .divide_card {
            border-top: 3px solid rgb(29, 185, 170);
            margin-block: 12px;
        }
        .tool_with_idea{
            display: flex;
            flex-direction: column;
            gap: 6px;
            padding-inline: 40px;
            padding-block: 20px;
        }
        .tool_with_idea > p{
            margin-top: 10px;
            margin-bottom: 0px;
        }
        .list_title{
            font-weight: 700;
        }
        .tool_name, .tool_name:visited {
            text-decoration: none;
            color: black;
            font-weight: 700;
            font-size: 40px;
            width: 100px;
        }
        .tool_type {
            width: 200px;
        }
        .tool_explain {
            font-size: 16px;
        }
        .buttons{
            position: absolute;
            bottom: 40px;
            display: flex;
            gap: 30px;
        }
        .delete_btn, .list_btn, .update_btn {
            font-size: 16px;
            font-family: 'ChosunGu';
            font-weight: 700;
            padding-inline: 14px;
            padding-block: 10px;
            border: 1px solid Gainsboro;
            border-radius: 6px;
        }
        .delete_btn {
            background-color:rgb(246, 88, 119);
        }
        .update_btn {
            background-color:rgb(160, 218, 103);
        }
        .list_content, .list_content:visited {
            margin-bottom: 10px;
            text-decoration: none;
            color: black;
        }
    </style>
</head>
<body>
    <header>
        <a href="{% url 'ideas:idea_list' %}" class="left_nav_container">My <span class="green">SW Idea</span> Manage</a>
        <div class="right_nav_container">
            <a href="{% url 'ideas:idea_create' %}" class="nav_menu">아이디어 등록</a>
            <a href="{% url 'ideas:idea_list' %}" class="nav_menu">아이디어 관리</a>
            <a href="{% url 'tools:tool_create' %}" class="nav_menu">개발툴 등록</a>
            <a href="{% url 'tools:tool_list' %}" class="nav_menu">개발툴 관리</a>
        </div>
    </header>
    <div class="under_navBar">
        <div class="tool_list_container">
            <div class="tool_list">
                <div class="tool_list_intro">
                    <div class="tool_list_title">🔧DevTool Detail🧐</div>
                    <div class="tool_list_intro_detail">
                        <p>개발툴 세부내용 페이지입니다. 자신이 다룰 수 있는 개발툴에 대한 상세내용을 확인해보아요~!</p>
                    </div>
                </div>
                <div class="tool_list_content">
                    <div class="tool_card">
                        <div class="tool_card_content">
                            <a href="#" class="tool_name">{{tool.name}}</a>
                            <div class="tool_type">{{tool.type}}</div>
                            <div class="tool_explain">{{tool.explain}}</div>
                        </div>
                        <div class="divide_card"></div>
                        <div class="tool_with_idea">
                            <p class="list_title">> 만들 수 있는 SW 목록</p>
                            {% for idea in related_ideas %}
                                <a href="{% url "ideas:idea_detail" idea.id %}" class="list_content">{{idea.title}}</a>
                            {% endfor %}
                        </div>
                    </div>
                    <div class="buttons">
                        <form action="{% url "tools:tool_delete" tool.pk %}" method="post">
                            {% csrf_token %}
                            <button type="submit" class="delete_btn">삭제</button>
                        </form>
                        <form action="{% url "tools:tool_list" %}">
                            {% csrf_token %}
                            <button type="submit" class="list_btn">목록</button>
                        </form>
                        <form action="{% url "tools:tool_update" tool.pk %}">
                            {% csrf_token %}
                            <button type="submit" class="update_btn">수정</button>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
</body>
</html>