myMovieReviews/review/urls.py
from django.urls import path
from .views import *

app_name = 'review'

urlpatterns = [
    # list
    path('review/', review_list, name='review_list'),
    
    # detail
    path('review/<int:pk>/', review_detail, name="review_detail"),
    
    # create
    path('review/create/', review_create, name="review_create"),
    
    # update
    path('review/<int:pk>/update/', review_update, name="review_update"),
    
    # delete
    path('review/<int:pk>/delete/', review_delete, name="review_delete"),
]

myMovieReviews/review/models.py
from django.db import models

class Review(models.Model):
    poster = models.FileField(upload_to='templates/poster/', blank=True)
    title = models.TextField()
    release = models.TextField()
    GENRE_CHOICES = [
        ('act', '액션'),
        ('dra', '드라마'),
        ('roco', '로맨스/코미디'),
        ('sf', 'SF'),
        ('hor', '스릴러'),
        ('ani', '애니메이션'),
        ('fan', '판타지'),
    ]
    genre = models.CharField(max_length=20, choices=GENRE_CHOICES, default='dra')
    stars = models.FloatField()
    director = models.TextField()
    actor = models.TextField()
    running_time = models.TextField()
    summary = models.TextField()

myMovieReviews/review/forms.py
from django import forms
from .models import Review

class GenreForm(forms.ModelForm):
    class Meta:
        model = Review
        fields = ['genre']

myMovieReviews/review/views.py
from django.urls import reverse
from django.shortcuts import render, redirect
from .models import Review
from .forms import GenreForm

def review_list(request):
    reviews = Review.objects.all()
    context = {
        'reviews': reviews
    }
    return render(request, 'review/list.html', context)

def calc_running_time(running_time):
    total_time = int(running_time.replace('분', '').strip())
    hour = total_time // 60
    min = total_time % 60
    return f"{hour}시간 {min}분"
    
def review_detail(request, pk):
    review = Review.objects.get(id=pk)
    review.running_time = calc_running_time(review.running_time)
    context = {
        'review': review
    }
    return render(request, 'review/detail.html', context)

def review_create(request):
    if request.method == 'POST':
        genre_form = GenreForm(request.POST)
        if genre_form.is_valid():
            genre = genre_form.cleaned_data['genre']
            review = Review.objects.create(
            poster = request.FILES['poster'],
            title = request.POST['title'],
            release = request.POST['release'],
            genre = genre,
            stars = request.POST['stars'],
            director = request.POST['director'],
            actor = request.POST['actor'],
            running_time = request.POST['running_time'],
            summary = request.POST['summary'],
        )
        return redirect(reverse('review:review_list'))
    genre_for_get = GenreForm()
    return render(request, 'review/create.html', {'genre_form': genre_for_get})

def review_update(request, pk):
    exist_review = Review.objects.get(id=pk)
    if request.method == 'POST':
        poster = request.FILES.get('poster') or exist_review.poster
        title = request.POST.get('title')
        release = request.POST.get('release')
        genre = GenreForm(request.POST, instance=exist_review)
        stars = request.POST.get('stars')
        director = request.POST.get('director')
        actor = request.POST.get('actor')
        running_time = request.POST.get('running_time')
        summary = request.POST.get('summary')
        
        if genre.is_valid():
            store_genre = genre.cleaned_data['genre']
        exist_review.poster = poster
        exist_review.title = title
        exist_review.release = release
        exist_review.genre = store_genre
        exist_review.stars = stars
        exist_review.director = director
        exist_review.actor = actor
        exist_review.running_time = running_time
        exist_review.summary = summary
        exist_review.save()
        return redirect('review:review_detail', pk=exist_review.pk)
    
    genre_for_get = GenreForm(instance=exist_review)
    context = {
        'review': exist_review,
        'genre_form': genre_for_get,
    }
    return render(request, 'review/update.html', context)

def review_delete(request, pk):
    if request.method == 'POST':
        review = Review.objects.get(id=pk)
        review.delete()
        return redirect('review:review_list')
    return redirect('review:review_list')

myMovieReviews/review/templates/review/create.html
<!DOCTYPE html>
<html lang="ko">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Pacifico&display=swap" rel="stylesheet">
    <title>My Movie reviews</title>
    <style>
        @font-face {
            font-family: '양진체';
            src: url('https://fastly.jsdelivr.net/gh/supernovice-lab/font@0.9/yangjin.woff') format('woff');
            font-weight: normal;
            font-style: normal;
        }

        * {
            box-sizing: border-box;
        }
        .body {
            width: 100vw;
        }

        .navBar_container {
            display: flex;
            justify-content: space-between;
            height: 60px;
            width: 100%;
            padding: 10px 25px;
            bottom: 0px;
            background-color: PaleGoldenRod;
        }
        .page_name, .page_name:visited {
            font-size: 25px;
            color: black;
            margin: 0px;
            font-family: "Pacifico", serif;
            text-decoration: none;
            transition: 0.2s ease 0s;
        }
        .page_name:hover {
            transform: scale(1.05, 1);
        }
        .Purple {
            color: Purple;
        }
        .add_review, .save_review {
            height: 40px;
            font-size: 20px;
            font-weight: 500;
            font-family: "Pacifico", serif;
            color: darkgoldenrod;
            border: 3px solid darkgoldenrod;
            border-radius: 8px;
            box-shadow: 2px 4px 5px gray;
            transition: 0.2s ease-out 0s;
        }
        .add_review:hover, .save_review:hover {
            color: white;
            background-color: darkgoldenrod;
        }

        .background {
            height:100vh;
            width: 100%;
            background-color: BlueViolet;
        }
        .register_container {
            width: 60%;
            height: fit-content;
            background-color: Lavender;
            margin: 18px 300px;
            border-radius: 5px;
            position: absolute;
            padding: 30px;
        }
        .register_header {
            display: flex;
            flex-direction:column;
            align-items: center;
        }
        .bold {
            font-weight: 700;
            font-size: 25px;
            font-family: '양진체';
        }
        .gold {
            color: gold;
            text-shadow: 2px 2px gray;
        }
        .register_body {
            padding: 40px 160px;
        }
        .field {
            margin-bottom: 20px;
            font-family: '양진체';
            font-size: 18px;
        }
        .summary {
            display: flex;
            flex-direction: column;
        }
        .save_review {
            position: relative;
            left: 600px;
        }
    </style>
</head>
<body>
    <header class="navBar_container">
        <a href="{% url 'review:review_list' %}" class="page_name">my<span class="Purple">Movie</span>reviews</a>
        <a href="{% url 'review:review_create' %}">
            <button type="submit" class="add_review">Add a New review</button>
        </a>
    </header>
    <div class="background">
    <div class="register_container">
        <div class="register_header">
            <p class="bold">Upload my <span class="gold">new</span> Movie review 🍿</p>
        </div>
        <div class="register_body">
            <form action="{% url 'review:review_create' %}" method="post" enctype="multipart/form-data">
                {% csrf_token %}
                <div class="field">
                    <label for="poster">포스터:</label>
                    <input type="file" id="poster" name="poster">
                </div>
                <div class="field">
                    <label for="title">제목:</label>
                    <input type="text" id="title" name="title">
                </div>
                <div class="field">
                    <label for="release">개봉년도:</label>
                    <input type="text" id="release" name="release">
                </div>
                <div class="field">
                    <label for="genre">장르: {{genre_form.genre}}</label>
                </div>
                <div class="field">
                    <label for="stars">별점:</label>
                    <input type="text" id="stars" name="stars">
                </div>
                <div class="field">
                    <label for="running_time">러닝타임:</label>
                    <input type="text" id="running_time" name="running_time">
                </div>
                <div class="field summary">
                    <label for="summary">리뷰:</label>
                    <textarea rows="10" id="summary" name="summary"></textarea>
                </div>
                <div class="field">
                    <label for="director">감독:</label>
                    <input type="text" id="director" name="director">
                </div>
                <div class="field">
                    <label for="actor">배우:</label>
                    <input type="text" id="actor" name="actor">
                </div>
                <button type="submit" class="save_review">Save</button>
            </form>
        </div>
    </div>
    </div>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/js/bootstrap.bundle.min.js"></script>
</body>
</html>

myMovieReviews/review/templates/review/detail.html
<!DOCTYPE html>
<html lang="ko">
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <link href="https://hangeul.pstatic.net/hangeul_static/css/NanumDaHaengCe.css" rel="stylesheet">
        <link rel="preconnect" href="https://fonts.googleapis.com">
        <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
        <link href="https://fonts.googleapis.com/css2?family=Pacifico&display=swap" rel="stylesheet">
        <title>My Movie reviews</title>
        <style>
            @font-face {
                font-family: 'TTTtangsbudaejjigaeB';
                src: url('https://fastly.jsdelivr.net/gh/projectnoonnu/noonfonts_2212@1.0/TTTtangsbudaejjigaeB.woff2') format('woff2');
                font-weight: 700;
                font-style: normal;
            }
            @font-face {
                font-family: '양진체';
                src: url('https://fastly.jsdelivr.net/gh/supernovice-lab/font@0.9/yangjin.woff') format('woff');
                font-weight: normal;
                font-style: normal;
            }

            * {
                box-sizing: border-box;
            }
            .body {
                width: 100vw;
            }

            .navBar_container {
                display: flex;
                justify-content: space-between;
                height: 60px;
                width: 100%%;
                padding: 10px 25px;
                bottom: 0px;
                background-color: PaleGoldenRod;
            }
            .page_name, .page_name:visited {
                text-decoration: none;
                color: black;
                font-family: "Pacifico", serif;
                font-size: 25px;
                transition: 0.2s ease-out 0s;
            }
            .page_name:hover {
                transform: scale(1.05, 1);
            }
            .Purple {
                color: Purple;
            }
            .add_review {
                height: 40px;
                font-size: 20px;
                font-weight: 500;
                font-family: "Pacifico", serif;
                color: darkgoldenrod;
                border: 3px solid darkgoldenrod;
                border-radius: 8px;
                box-shadow: 2px 4px 5px gray;
                transition: 0.2s ease-out 0s;
            }
            .add_review:hover {
                color: white;
                background-color: darkgoldenrod;
            }

            .review_container {
                padding: 5px 30px;
                background-color: BlueViolet;
                height: 100vh;
            }
            .review_title {
                display: flex;
                justify-content: space-between;
                align-items: center;
                margin-inline: 15px;
            }
            .movie_title {
                font-size: 35px;
                font-family: 'TTTtangsbudaejjigaeB';
                color: white;
            }
            .button {
                display: flex;
                gap: 5px;
            }
            .deco_button {
                height: 40px;
                font-size: 16px;
                font-weight: 500;
                font-family: 'TTTtangsbudaejjigaeB';
                border: 3px solid purple;
                border-radius: 8px;
                box-shadow: 2px 4px 4px RebeccaPurple;
                transition: 0.2s ease-out 0s;
                color: purple;
            }
            .deco_button:hover {
                color: white;
                background-color: purple;
            }

            .review_content {
                display: flex;
                flex-direction: column;
                gap: 20px;
            }
            .about_movie {
                display: flex;
            }
            .movie_img {
                width: 200px;
                height: 270px;
                margin: 20px;
                border-block: 12px dashed black;
                border-inline: 5px solid black;
                background-color: white;
                border-radius: 4px;
            }
            .movie_img > img {
                width: 100%;
                height: 100%;
            }
            .movie_info {
                display: flex;
                flex-direction: column;
                margin-left: 20px;
                margin-top: 20px;
            }
            .movie_info > p {
                margin-bottom: 10px;
                font-family: 'TTTtangsbudaejjigaeB';
                font-weight: 400;
                font-size: 16px;
            }

            .more_info, .about_movie {
                background-color: Lavender;
                padding: 18px;
                border-radius: 8px;
            }
            .more_info {
                font-family: 'NanumDaHaengCe';
                font-weight: 700;
                font-size: 22px;
                padding-block: 36px;
            }
        </style>
    </head>
    <body>
        <header class="navBar_container">
            <a href="{% url 'review:review_list' %}" class="page_name">my<span class="Purple">Movie</span>reviews</a>
            <a href="{% url 'review:review_create' %}">
                <button type="submit" class="add_review">Add a New review</button>
            </a>
        </header>
        <div class="review_container">
            <div class="review_title">
                <p href="{% url 'review:review_detail' review.pk %}" class="movie_title">📽️ {{review.title}}</p>
                <div class="button">
                    <form action="{% url 'review:review_update' review.pk %}">
                        {% csrf_token %}
                        <button type="submit" class="deco_button">수정</button>
                    </form>
                    <form action="{% url 'review:review_delete' review.pk %}" method="post">
                        {% csrf_token %}
                        <button type="submit" class="deco_button">삭제</button>
                    </form>
                </div>
            </div>
            <div class="review_content">
                <div class="about_movie">
                    <div class="movie_img"><img src="{{review.poster.url}}"></div>
                    <div class="movie_info">
                        <p>개봉년도 | {{review.release}}</p>
                        <p>감독 | {{review.director}}</p>
                        <p>주연 | {{review.actor}}</p>
                        <p>장르 | {{review.get_genre_display}}</p>
                        <p>별점 | {{review.stars}}</p>
                        <p>러닝타임 | {{review.running_time}}</p>
                    </div>
                </div>
                <div class="more_info">✍️관람후기 : {{review.summary}}</div>
            </div>
        </div>
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/js/bootstrap.bundle.min.js"></script>
    </body>
    </html>
    

myMovieReviews/review/templates/review/list.html
<!DOCTYPE html>
<html lang="ko">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>My Movie reviews</title>
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Pacifico&display=swap" rel="stylesheet">
    <style>
        @font-face {
            font-family: 'TTTtangsbudaejjigaeB';
            src: url('https://fastly.jsdelivr.net/gh/projectnoonnu/noonfonts_2212@1.0/TTTtangsbudaejjigaeB.woff2') format('woff2');
            font-weight: 700;
            font-style: normal;
        }

        * {
            box-sizing: border-box;
        }
        .body {
            width: 100vw;
        }

        .navBar_container {
            display: flex;
            justify-content: space-between;
            height: 60px;
            width: 100%;
            padding: 10px 25px;
            bottom: 0px;
            background-color: PaleGoldenRod;
        }
        .page_name{
            font-size: 25px;
            color: black;
            margin: 0px;
            font-family: "Pacifico", serif;
        }
        .Purple {
            color: Purple;
        }
        .add_review {
            height: 40px;
            font-size: 20px;
            font-weight: 500;
            font-family: "Pacifico", serif;
            color: darkgoldenrod;
            border: 3px solid darkgoldenrod;
            border-radius: 8px;
            box-shadow: 2px 4px 5px gray;
            transition: 0.2s ease-out 0s;
        }
        .add_review:hover {
            color: white;
            background-color: darkgoldenrod;
        }

        .list_container {
            display: flex;
            align-items: center;
            justify-content: center;
            width: 100%;
            height: 100vh;
            background-color: indigo;
        }
        .review_list {
            display: flex;
            gap: 30px;
            overflow-x: scroll;
            overflow-y: clip;
            height: 70%;
            padding-top: 24px;
            padding-inline: 30px;
        }
        .review_list::-webkit-scrollbar {
            width: 8px;
        }
        .review_list::-webkit-scrollbar-thumb {
            background: #b597f2;
            border-radius: 10px;
        }

        .review_card {
            width: 280px;
            height: fit-content;
            background-color: BlueViolet;
            display: flex;
            flex-direction: column;
            justify-content: center;
            border-radius: 10px;
            padding: 0 18px 22px 18px;
            border: 3px groove palegoldenrod;
            transition: 0.3s ease-out 0s;
            position: relative;
        }
        .dot_1, .dot_2, .dot_3, .dot_4, .dot_5, .dot_6, .dot_7 {
            position: absolute;
            bottom: -10px;
            right: 246px;
            width: 22px;
            height: 20px;
            background-color: indigo;
            border-top: 4px groove palegoldenrod;
            border-radius: 50%;
        }
        .dot_2 {
            right: 206px;
        }
        .dot_3 {
            right: 166px;
        }
        .dot_4 {
            right: 126px;
        }
        .dot_5 {
            right: 86px;
        }
        .dot_6 {
            right: 46px;
        }
        .dot_7 {
            right: 6px;
        }

        .review_card:hover {
            transform: scale(1.05,1.05);
            background-color: palegoldenrod;
        }
        .review_card:hover .divide, .review_card:hover .movie_info, .review_card:hover .bold {
            color: indigo;
            border-color: indigo;
        }

        .movie_ticket {
            font-family: "Pacifico", serif;
            color: White;
            margin-inline: 10%;
            background-color: indigo;
            width: 80%;
            padding-top: 4px;
            padding-inline: 10%;
            height: 40px;
            border-bottom-left-radius: 24px;
            border-bottom-right-radius: 24px;
        }
        .movie_img {
            width: 200px;
            height: 270px;
            margin: 20px;
            border-block: 12px dashed black;
            border-inline: 5px solid black;
            background-color: white;
            border-radius: 4px;
        }
        .movie_img > img {
            width: 100%;
            height: 100%;
        }
        .divide {
            border-top: 2px dotted palegoldenrod;
            border-width: 6px;
            margin-bottom: 20px;
            width: 64%;
            margin-inline: 18%;
        }
        .movie_info {
            display: flex;
            flex-direction: column;
            font-family: 'TTTtangsbudaejjigaeB';
            color: White;
        }
        .movie_info > p {
            margin: 10px;
            font-size: 16px;
        }
        .bold {
            text-decoration: none;
            color: white;
            margin: 10px;
            transition: 0.2s ease-in;
            height: 40px;
            font-size: 1.4rem;
        }
        .review_card:hover .bold:hover {
            color: darkgoldenrod;
        }
    </style>
</head>
<body>
    <header class="navBar_container">
        <div class="page_name">my<span class="Purple">Movie</span>reviews</div>
        <a href="{% url 'review:review_create' %}">
            <button type="submit" class="add_review">Add a New review</button>
        </a>
    </header>
    <div class="list_container">
        <div class="review_list">
            {% for review in reviews %}
            <div class="review_card">
                <div class="movie_ticket">MOVIE -TICKET</div>
                <div class="movie_img"><img src="{{ review.poster.url }}"></div>
                <div class="divide"></div>
                <div class="movie_info">
                    <a href="{% url 'review:review_detail' review.pk %}" class="bold">{{review.title}}</a>
                    <p>{{review.release}}</p>
                    <p>{{review.get_genre_display}}</p>
                    <p>{{review.stars}}</p>
                </div>
                <div class="dot_1"></div>
                <div class="dot_2"></div>
                <div class="dot_3"></div>
                <div class="dot_4"></div>
                <div class="dot_5"></div>
                <div class="dot_6"></div>
                <div class="dot_7"></div>
            </div>
            {% endfor %}
        </div>
    </div>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/js/bootstrap.bundle.min.js"></script>
</body>
</html>

myMovieReviews/review/templates/review/update.html
<!DOCTYPE html>
<html lang="ko">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Pacifico&display=swap" rel="stylesheet">
    <title>My Movie reviews</title>
    <style>
        @font-face {
            font-family: '양진체';
            src: url('https://fastly.jsdelivr.net/gh/supernovice-lab/font@0.9/yangjin.woff') format('woff');
            font-weight: normal;
            font-style: normal;
        }

        * {
            box-sizing: border-box;
        }
        .body {
            width: 100vw;
        }

        .navBar_container {
            display: flex;
            justify-content: space-between;
            height: 60px;
            width: 100%;
            padding: 10px 25px;
            bottom: 0px;
            background-color: PaleGoldenRod;
        }
        .page_name, .page_name:visited {
            font-size: 25px;
            color: black;
            margin: 0px;
            font-family: "Pacifico", serif;
            text-decoration: none;
            transition: 0.2s ease-out 0s;
        }
        .page_name:hover {
            transform: scale(1.05, 1);
        }
        .Purple {
            color: Purple;
        }
        .add_review {
            height: 40px;
            font-size: 20px;
            font-weight: 500;
            font-family: "Pacifico", serif;
            color: darkgoldenrod;
            border: 3px solid darkgoldenrod;
            border-radius: 8px;
            box-shadow: 2px 4px 5px gray;
            transition: 0.2s ease-out 0s;
        }
        .save_review {
            font-family: "Pacifico", serif;
            height: 40px;
            font-size: 20px;
            font-weight: 500;
            border: 3px solid purple;
            border-radius: 8px;
            box-shadow: 2px 4px 4px RebeccaPurple;
            transition: 0.2s ease-out 0s;
            color: purple;
        }
        .add_review:hover {
            color: white;
            background-color: darkgoldenrod;
        }
        .save_review:hover {
            color: white;
            background-color: purple;
        }

        .background {
            height:100vh;
            width: 100%;
            background-color: BlueViolet;
        }
        .register_container {
            width: 60%;
            height: fit-content;
            background-color: Lavender;
            margin: 18px 300px;
            border-radius: 5px;
            position: absolute;
            padding: 30px;
        }
        .register_header {
            display: flex;
            flex-direction:column;
            align-items: center;
        }
        .bold {
            font-weight: 700;
            font-size: 25px;
            font-family: '양진체';
        }
        .red {
            color: red;
            text-shadow: 2px 2px gray;
        }
        .register_body {
            padding: 40px 160px;
        }
        .field {
            margin-bottom: 20px;
            font-family: '양진체';
            font-size: 18px;
        }
        .summary {
            display: flex;
            flex-direction: column;
        }
        .save_review {
            position: relative;
            left: 600px;
        }
    </style>
</head>
<body>
    <header class="navBar_container">
        <a href="{% url 'review:review_list' %}" class="page_name">my<span class="Purple">Movie</span>reviews</a>
        <a href="{% url 'review:review_create' %}">
            <button type="submit" class="add_review">Add a New review</button>
        </a>
    </header>
    <div class="background">
    <div class="register_container">
        <div class="register_header">
            <p class="bold"><span class="red">Rewrite</span> my Movie review 🍿</p>
        </div>
        <div class="register_body">
            <form action="{% url 'review:review_update' review.pk %}" method="post" enctype="multipart/form-data">
                {% csrf_token %}
                <div class="field">
                    <label for="poster">새롭게 변경할 포스터:</label>
                    <input type="file" id="poster" name="poster">
                </div>
                <div class="field">
                    <label for="title">제목:</label>
                    <input type="text" id="title" name="title" value="{{review.title}}">
                </div>
                <div class="field">
                    <label for="release">개봉년도:</label>
                    <input type="text" id="release" name="release" value="{{review.release}}">
                </div>
                <div class="field">
                    <label for="genre">장르:</label>
                    {{genre_form.genre}}
                </div>
                <div class="field">
                    <label for="stars">별점:</label>
                    <input type="text" id="stars" name="stars" value="{{review.stars}}">
                </div>
                <div class="field">
                    <label for="running_time">러닝타임:</label>
                    <input type="text" id="running_time" name="running_time" value="{{review.running_time}}">
                </div>
                <div class="field summary">
                    <label for="summary">리뷰:</label>
                    <textarea rows="10" id="summary" name="summary">{{review.summary}}</textarea>
                </div>
                <div class="field">
                    <label for="director">감독:</label>
                    <input type="text" id="director" name="director" value="{{review.director}}">
                </div>
                <div class="field">
                    <label for="actor">배우:</label>
                    <input type="text" id="actor" name="actor" value="{{review.actor}}">
                </div>
                <button type="submit" class="save_review">Save</button>
            </form>
        </div>
    </div>
</div>
</body>
</html>